### Tuesday, May 2nd, 2023
The OIT research cluster is still down, so I'm proceeding with WADI data processing using Google Colab. 

When the cluster is back up I will synchronize the processed data and run GDN.

The WADI processing script included in GDN (https://github.com/d-ailin/GDN/blob/main/scripts/process_wadi.py) makes some assumptions about the WADI data format that aren't true with the version of WADI that I have, so I'll try to adapt their normalization and downsampling techniques rather than try to run their script directly. Hopefully that will also give me a better understanding of the transformations they're applying.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')
path_to_wadi = "/content/drive/MyDrive/iTrust/WADI"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

We'll work on the training data first:

In [3]:
# load data from disk
training_data = pd.read_csv(
    path_to_wadi + '/WADI.A2_19 Nov 2019/WADI_14days_new.csv'
)

training_data

,Row,Date,Time,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
0,1,9/25/2017,00:00.0,171.155,0.619473,11.5759,504.645,0.318319,0.001157,0,...,1,1,1,1,1,1,1,67.9651,1,0.68
1,2,9/25/2017,00:01.0,171.155,0.619473,11.5759,504.645,0.318319,0.001157,0,...,1,1,1,1,1,1,1,67.9651,1,0.68
2,3,9/25/2017,00:02.0,171.155,0.619473,11.5759,504.645,0.318319,0.001157,0,...,1,1,1,1,1,1,1,67.9651,1,0.68
3,4,9/25/2017,00:03.0,171.155,0.607477,11.5725,504.673,0.318438,0.001207,0,...,1,1,1,1,1,1,1,67.1948,1,0.68
4,5,9/25/2017,00:04.0,171.155,0.607477,11.5725,504.673,0.318438,0.001207,0,...,1,1,1,1,1,1,1,67.1948,1,0.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784566,1048567,10/7/17,16:06.0,175.855,0.589478,11.8941,479.191,0.331571,0.001128,0,...,1,1,1,1,1,1,1,60.6305,1,0.25
784567,1048568,10/7/17,16:07.0,175.855,0.589478,11.8941,479.191,0.331571,0.001128,0,...,1,1,1,1,1,1,1,60.6305,1,0.25
784568,1048569,10/7/17,16:08.0,175.855,0.589478,11.8941,479.191,0.331571,0.001128,0,...,1,1,1,1,1,1,1,60.6305,1,0.25
784569,1048570,10/7/17,16:09.0,175.896,0.613476,11.8913,479.224,0.331622,0.001173,0,...,1,1,1,1,1,1,1,60.4477,1,0.25
784570,1048571,10/7/17,16:10.0,175.896,0.613476,11.8913,479.224,0.331622,0.001173,0,...,1,1,1,1,1,1,1,60.4477,1,0.25

In [4]:
# drop timestamps
training_data = training_data.set_index("Row").drop(columns=["Date","Time"])

# fill in missing values
training_data = training_data.fillna(training_data.mean()).fillna(0)

training_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
1,171.155,0.619473,11.5759,504.645,0.318319,0.001157,0,0,47.8911,1,...,1,1,1,1,1,1,1,67.9651,1,0.68
2,171.155,0.619473,11.5759,504.645,0.318319,0.001157,0,0,47.8911,1,...,1,1,1,1,1,1,1,67.9651,1,0.68
3,171.155,0.619473,11.5759,504.645,0.318319,0.001157,0,0,47.8911,1,...,1,1,1,1,1,1,1,67.9651,1,0.68
4,171.155,0.607477,11.5725,504.673,0.318438,0.001207,0,0,47.7503,1,...,1,1,1,1,1,1,1,67.1948,1,0.68
5,171.155,0.607477,11.5725,504.673,0.318438,0.001207,0,0,47.7503,1,...,1,1,1,1,1,1,1,67.1948,1,0.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048567,175.855,0.589478,11.8941,479.191,0.331571,0.001128,0,0,48.1129,1,...,1,1,1,1,1,1,1,60.6305,1,0.25
1048568,175.855,0.589478,11.8941,479.191,0.331571,0.001128,0,0,48.1129,1,...,1,1,1,1,1,1,1,60.6305,1,0.25
1048569,175.855,0.589478,11.8941,479.191,0.331571,0.001128,0,0,48.1129,1,...,1,1,1,1,1,1,1,60.6305,1,0.25
1048570,175.896,0.613476,11.8913,479.224,0.331622,0.001173,0,0,48.0348,1,...,1,1,1,1,1,1,1,60.4477,1,0.25
1048571,175.896,0.613476,11.8913,479.224,0.331622,0.001173,0,0,48.0348,1,...,1,1,1,1,1,1,1,60.4477,1,0.25

In [5]:
# create normalizer
from sklearn.preprocessing import MinMaxScaler
normalizer = MinMaxScaler(feature_range=(0,1)).fit(training_data.values)

In [6]:
# normalize training data
train_normed = normalizer.transform(training_data.values)
training_data = pd.DataFrame(
    train_normed,
    columns=training_data.columns,
    index=training_data.index
)

training_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
1,0.798629,0.300814,0.963590,0.958437,0.515464,0.000168,0.0,0.0,0.276747,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.221481,0.0,0.300885
2,0.798629,0.300814,0.963590,0.958437,0.515464,0.000168,0.0,0.0,0.276747,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.221481,0.0,0.300885
3,0.798629,0.300814,0.963590,0.958437,0.515464,0.000168,0.0,0.0,0.276747,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.221481,0.0,0.300885
4,0.798629,0.294989,0.963307,0.958490,0.516021,0.000192,0.0,0.0,0.272455,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.213922,0.0,0.300885
5,0.798629,0.294989,0.963307,0.958490,0.516021,0.000192,0.0,0.0,0.272455,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.213922,0.0,0.300885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048567,0.820560,0.286249,0.990078,0.910094,0.577554,0.000154,0.0,0.0,0.283508,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149502,0.0,0.110619
1048568,0.820560,0.286249,0.990078,0.910094,0.577554,0.000154,0.0,0.0,0.283508,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149502,0.0,0.110619
1048569,0.820560,0.286249,0.990078,0.910094,0.577554,0.000154,0.0,0.0,0.283508,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149502,0.0,0.110619
1048570,0.820751,0.297902,0.989845,0.910157,0.577793,0.000176,0.0,0.0,0.281127,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.147708,0.0,0.110619
1048571,0.820751,0.297902,0.989845,0.910157,0.577793,0.000176,0.0,0.0,0.281127,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.147708,0.0,0.110619

In [7]:
# downsample by 10x using median
training_data = training_data.rolling(window=10, step=10).median()

training_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.798629,0.294989,0.963307,0.958490,0.516021,0.000192,0.0,0.0,0.272455,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.213922,0.0,0.300885
21,0.798657,0.300815,0.963328,0.958585,0.516120,0.000190,0.0,0.0,0.331281,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.171732,0.0,0.300885
31,0.798634,0.294989,0.963278,0.958613,0.516099,0.000188,0.0,0.0,0.325523,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.147179,0.0,0.300885
41,0.798657,0.292077,0.962775,0.958639,0.515459,0.000221,0.0,0.0,0.263579,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149070,0.0,0.300885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048531,0.820735,0.280422,0.989932,0.909935,0.576994,0.000137,0.0,0.0,0.282255,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.148616,0.0,0.110619
1048541,0.820639,0.318293,0.989845,0.909935,0.577441,0.000156,0.0,0.0,0.283929,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149549,0.0,0.110619
1048551,0.820690,0.296445,0.989424,0.910014,0.578053,0.000158,0.0,0.0,0.287056,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.148126,0.0,0.110619
1048561,0.820607,0.294989,0.989653,0.910018,0.576963,0.000134,0.0,0.0,0.288077,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149112,0.0,0.110619
1048571,0.820560,0.286249,0.990078,0.910094,0.577554,0.000154,0.0,0.0,0.283508,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149502,0.0,0.110619

In [8]:
# knock out first 2160 samples (warmup period)
training_data = training_data.iloc[2160:]
training_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
21601,0.781150,0.312468,0.965130,0.963362,0.637184,0.000130,0.0,0.0,0.157283,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169876,0.0,0.247788
21611,0.781266,0.306641,0.965255,0.963383,0.637291,0.000145,0.0,0.0,0.117956,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.170539,0.0,0.247788
21621,0.781154,0.303728,0.965405,0.963394,0.637188,0.000175,0.0,0.0,0.114344,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.171938,0.0,0.247788
21631,0.781294,0.303728,0.965422,0.963346,0.637767,0.000142,0.0,0.0,0.117185,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169281,0.0,0.247788
21641,0.781336,0.305184,0.965363,0.963393,0.637502,0.000104,0.0,0.0,0.079742,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.168962,0.0,0.247788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048531,0.820735,0.280422,0.989932,0.909935,0.576994,0.000137,0.0,0.0,0.282255,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.148616,0.0,0.110619
1048541,0.820639,0.318293,0.989845,0.909935,0.577441,0.000156,0.0,0.0,0.283929,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149549,0.0,0.110619
1048551,0.820690,0.296445,0.989424,0.910014,0.578053,0.000158,0.0,0.0,0.287056,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.148126,0.0,0.110619
1048561,0.820607,0.294989,0.989653,0.910018,0.576963,0.000134,0.0,0.0,0.288077,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149112,0.0,0.110619
1048571,0.820560,0.286249,0.990078,0.910094,0.577554,0.000154,0.0,0.0,0.283508,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.149502,0.0,0.110619

In [9]:
# no attacks in training data
training_data = training_data.assign(attack=0)

training_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW,attack
Row,,,,,,,,,,,,,,,,,,,,,
21601,0.781150,0.312468,0.965130,0.963362,0.637184,0.000130,0.0,0.0,0.157283,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.169876,0.0,0.247788,0
21611,0.781266,0.306641,0.965255,0.963383,0.637291,0.000145,0.0,0.0,0.117956,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.170539,0.0,0.247788,0
21621,0.781154,0.303728,0.965405,0.963394,0.637188,0.000175,0.0,0.0,0.114344,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.171938,0.0,0.247788,0
21631,0.781294,0.303728,0.965422,0.963346,0.637767,0.000142,0.0,0.0,0.117185,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.169281,0.0,0.247788,0
21641,0.781336,0.305184,0.965363,0.963393,0.637502,0.000104,0.0,0.0,0.079742,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.168962,0.0,0.247788,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048531,0.820735,0.280422,0.989932,0.909935,0.576994,0.000137,0.0,0.0,0.282255,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.148616,0.0,0.110619,0
1048541,0.820639,0.318293,0.989845,0.909935,0.577441,0.000156,0.0,0.0,0.283929,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.149549,0.0,0.110619,0
1048551,0.820690,0.296445,0.989424,0.910014,0.578053,0.000158,0.0,0.0,0.287056,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.148126,0.0,0.110619,0
1048561,0.820607,0.294989,0.989653,0.910018,0.576963,0.000134,0.0,0.0,0.288077,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.149112,0.0,0.110619,0
1048571,0.820560,0.286249,0.990078,0.910094,0.577554,0.000154,0.0,0.0,0.283508,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.149502,0.0,0.110619,0

In [10]:
# save to disk
training_data.to_csv(
    '/content/drive/MyDrive/WADI-processed/train.csv'
)

In [11]:
# sanity check
!head '/content/drive/MyDrive/WADI-processed/train.csv'

Row,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,1_MV_002_STATUS,1_MV_003_STATUS,1_MV_004_STATUS,1_P_001_STATUS,1_P_002_STATUS,1_P_003_STATUS,1_P_004_STATUS,1_P_005_STATUS,1_P_006_STATUS,2_DPIT_001_PV,2_FIC_101_CO,2_FIC_101_PV,2_FIC_101_SP,2_FIC_201_CO,2_FIC_201_PV,2_FIC_201_SP,2_FIC_301_CO,2_FIC_301_PV,2_FIC_301_SP,2_FIC_401_CO,2_FIC_401_PV,2_FIC_401_SP,2_FIC_501_CO,2_FIC_501_PV,2_FIC_501_SP,2_FIC_601_CO,2_FIC_601_PV,2_FIC_601_SP,2_FIT_001_PV,2_FIT_002_PV,2_FIT_003_PV,2_FQ_101_PV,2_FQ_201_PV,2_FQ_301_PV,2_FQ_401_PV,2_FQ_501_PV,2_FQ_601_PV,2_LS_001_AL,2_LS_002_AL,2_LS_101_AH,2_LS_101_AL,2_LS_201_AH,2_LS_201_AL,2_LS_301_AH,2_LS_301_AL,2_LS_401_AH,2_LS_401_AL,2_LS_501_AH,2_LS_501_AL,2_LS_601_AH,2_LS_601_AL,2_LT_001_PV,2_LT_002_PV,2_MCV_007_CO,2_MCV_101_CO,2_MCV_201_CO,2_MCV_301_CO,2_MCV_401_CO,2_MCV_501_CO,2_MCV_601_CO,2_MV_001_STATUS,2_MV_002_STATUS,2_MV_003_STATUS,2_MV_004_STATUS,2_MV_005_STATUS,2_MV_006_STATUS,2_MV_009_STATUS,2_MV_101_STATUS,2_MV_201_STATUS,2_MV_301_STATUS,2_MV_401_STATUS,2_MV_501_STATUS,2_MV_601_STATUS,2_P_001_STATUS,2_P_002_STATUS,2_P_003_SPEED,2_P_003_STATUS,2_P_004_SPEED,2_P_004_STATUS,2_PIC_003_CO,2_PIC_003_PV,2_PIC_003_SP,2_PIT_001_PV,2_PIT_002_PV,2_PIT_003_PV,2_SV_101_STATUS,2_SV_201_STATUS,2_SV_301_STATUS,2_SV_401_STATUS,2_SV_501_STATUS,2_SV_601_STATUS,2A_AIT_001_PV,2A_AIT_002_PV,2A_AIT_003_PV,2A_AIT_004_PV,2B_AIT_001_PV,2B_AIT_002_PV,2B_AIT_003_PV,2B_AIT_004_PV,3_AIT_001_PV,3_AIT_002_PV,3_AIT_003_PV,3_AIT_004_PV,3_AIT_005_PV,3_FIT_001_PV,3_LS_001_AL,3_LT_001_PV,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW,attack
21601,0.78114982432073,0.3124677077870365,0.9651303139020919,0.9633619420772646,0.6371835658028513,0.00012975289001645757,0.0,0.0,0.15728254773342454,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9060131561418732,0.26207888340432606,0.053927465584515805,0.07142857142857142,0.21475085134439703,0.056910753570799576,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.2601771244194872,0.03518469542025549,0.09302325581395346,0.2222358489864533,0.043497469629451835,0.0,0.22129254431067186,0.037921262896909044,0.09302325581395346,0.9835225224051122,0.5474779378407758,0.0,0.052701286413670355,0.05696055330460252,0.007812357620115126,0.035183773771323014,0.0433497879251863,0.03442806073943061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3417800565305953,0.440654622052985,0.0,0.259362,0.25765,0.279043,0.0,0.28264900000000004,0.31832,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.001997902241660025,0.0,0.9420095315394061,0.0,1.0,0.001115957532431126,0.0,0.6629077991069972,0.9036073613732255,0.0011098558342175777,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,6.961699262186454e-42,0.5136423405654185,0.41700784448542016,0.5000071110605435,0.017889655126836768,0.8668494526075952,0.3607025931507559,0.0,0.9982299988666204,0.18494058647588157,0.5124910200952144,0.3849416083747354,0.4574719299107121,0.0,0.055022270004606355,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16987590592599494,0.0,0.24778761061946905,0
21611,0.7812664772223543,0.30664102713517083,0.9652551755138056,0.963382833614103,0.6372913279577195,0.000145231652125267,0.0,0.0,0.1179558145772881,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9071293039198389,0.25185498721526334,0.053754777500959514,0.07142857142857142,0.20171081898121862,0.05347251841396693,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.25953289386824846,0.03523292558145588,0.09302325581395346,0.2149915539081019,0.043197053952090655,0.0,0.22376192825982333,0.037481888205702155,0.09302325581395346,0.9850429856685478,0.5389055799501835,0.0,0.05232025067217514,0.05249126262888633,0.007812357620115126,0.0358257609921346,0.04379205576585517,0.03439471707594927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3621573654111607,0.5445249476279206,0.0,0.261453,0.250612,0.278144,0.0,0.270996,0.30848600000000004,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.00198986013978231,0.0,0.9370637447711808,0.0,1.0,0.0011327308414000297,0.0,0.6661017501548097,0.9059323324237798,0.0011263899016005158,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,7.34142831285117e-42,0.5136423405654185,0.4215395193299365,0.5138879012415911,0.015988342315610027,0.8548299897665617,0.3603536722073333,0.0,0.9982299988666204,0.033442304483078805,0.5997684447793525,0.3849351863693486,0.4573359243165335,0.0,0.05678851174934785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.17053931117729898,0.0,0.24778761061946905,0
21621,0.7811544904367951,0.3037279296078317,0.965405009447862,0.963394228997833,0.6371882511139326,0.00017459143111426298,0.0,0.0,0.1143438025799215,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9075865644611346,0.24151862167950475,0.05382565953123212,0.07142857142857142,0.18987663671993016,0.051795772248733586,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.2587932597481161,0.035622070306757694,0.09302325581395346,0.20734718354856932,0.04344811284934204,0.0,0.22616192977362193,0.03726757926968976,0.09302325581395346,0.9850212647647844,0.5304530553201687,0.0,0.053995163176157684,0.05271994941311803,0.007812357620115126,0.03560619534711991,0.04345627420668302,0.034859612062189065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3616314993755303,0.5857918311130654,0.0,0.263774,0.24333400000000002,0.27765,0.0,0.25958400000000004,0.298825,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.0019863273593145993,0.0,0.9521581236602777,0.0,1.0,0.0012110062832549158,0.0,0.6699801192842942,0.9079077063624671,0.0012680842346171565,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,6.569312576499582e-42,0.5136423405654185,0.41878926149326645,0.5138879012415911,0.022206765289971675,0.8785358459964083,0.36072486470033605,0.0,0.9982299988666204,0.055908190380015495,0.5906896786567161,0.38485078286997954,0.45742366986116484,0.0,0.08746736292427926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.17193776159609803,0.0,0.24778761061946905,0
21631,0.7812944739187442,0.303727686809238,0.9654216576627571,0.9633457986169803,0.6377668870324643,0.0001418570205363273,0.0,0.0,0.1171846423955718,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9100600919561751,0.22991156881328836,0.055156956094906034,0.07142857142857142,0.1805537303060441,0.0482991055463018,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.25780229364541446,0.03578641623276589,0.09302325581395346,0.19910688953722497,0.04426599744572833,0.0,0.2280920229752576,0.038219144043489986,0.09302325581395346,0.9849083160652148,0.5305198195653477,0.0,0.05343114804081495,0.048991330859465686,0.007812357620115126,0.036163130122488216,0.04438822348781124,0.035590106574780206,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.36485242884375424,0.5431013529935989,0.0,0.265712,0.235431,0.27636299999999997,0.0,0.25127,0.288845,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.0019776964606922657,0.0,0.9524562444069844,0.0,1.0,0.001384090857234034,0.0,0.6770850307988137,0.9089875507366582,0.0013741647113819757,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,7.721157363515886e-42,0.5136423405654185,0.42044566678126216,0.5138879012415911,0.015884916714304143,0.8788737425421402,0.36102924254459845,0.0,0.9982299988666204,0.15617616099203685,0.5329800322068267,0.38484848929662707,0.45738418436608075,0.0,0.06160727998771165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16928070580037974,0.0,0.24778761061946905,0
21641,0.7813364689633289,0.30518399277431385,0.9653633889106241,0.9633932793825222,0.6375021669563748,0.00010356439322366755,0.0,0.0,0.07974164207856815,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9105497567877987,0.22234584237594093,0.05440018618346618,0.07142857142857142,0.17398556765940665,0.046456119925314225,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.2568354348961429,0.03619951086688297,0.09302325581395346,0.19340791141537317,0.04400541696491246,0.0,0.22950069666272588,0.03840490603628838,0.09302325581395346,0.9833748202595214,0.5304376481866659,0.0,0.05362063793743982,0.04640614622697183,0.007812357620115126,0.03644602558444397,0.044579821067292566,0.03576046586693486,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3672023926904622,0.5735003067094127,0.0,0.2670105,0.2300435,0.27563550000000003,0.0,0.245293,0.2811005,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.0019961358514261696,0.0,0.9477237726582175,0.0,1.0,0.0014600366728432378,0.0,0.6753088029201835,0.9100488634587875,0.0014515992602920692,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,7.7464726335602e-42,0.5136423405654185,0.41828921461387125,0.5138879012415911,0.015892186245386353,0.8668494526075952,0.36095500404599834,0.0,0.9982299988666204,0.17266892311115484,0.5215206850870968,0.3849530762414975,0.4574118242126396,0.0,0.05875633543234393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16896176096802207,0.0,0.24778761061946905,0
21651,0.7812244821777696,0.3008143464833052,0.9654299817702048,0.963394228997833,0.6371367126920391,0.00015792646421450632,0.0,0.0,0.09141590870296756,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.91201875128267,0.2138133121314196,0.05523252884777021,0.07142857142857142,0.16872611347180771,0.043964578318670886,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.2559660314054187,0.03604524041975568,0.09302325581395346,0.18708787402194949,0.04498205939338419,0.0,0.23098190653260864,0.03824314002474234,0.09302325581395346,0.9842175913255399,0.530418817245718,0.0,0.053987624699257594,0.044494392975506544,0.007812357620115126,0.03629664073920567,0.045488452184589384,0.03596493534357042,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3773088805626763,0.6518558812976702,0.0,0.268472,0.223815,0.274711,0.0,0.240317,0.27301600000000004,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.0019975097104969457,0.0,0.9408160079915092,0.0,1.0,0.001552196687122382,0.0,0.6841573509761112,0.9121098836813277,0.0015225776495573972,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,6.657916021654682e-42,0.5136423405654185,0.4211332312404288,0.5138879012415911,0.015895490577696403,0.8788737425421402,0.3611183287429194,0.0,0.9982299988666204,0.11794001737262572,0.5649560726125537,0.38498656241244283,0.4574271796829501,0.0,0.0631431423744413,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16869433799319905,0.0,0.24778761061946905,0
21661,0.7810098408387809,0.29790027776159117,0.9654965746297854,0.9633296551566961,0.6376099291112431,0.0001392764199094911,0.0,0.0,0.08323477773171728,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9127568490068085,0.20320226184507692,0.05362621695585724,0.07142857142857142,0.161098181475188,0.044889573604851164,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.25432467968251743,0.03676605008920267,0.09302325581395346,0.17905599619111576,0.04435091442568101,0.0,0.23269018619091902,0.038535642761732235,0.09302325581395346,0.9835181782243596,0.5304693184055328,0.0,0.05219723643548739,0.0453060603977498,0.007812357620115126,0.0366131227267687,0.04481377997773427,0.03602549050253653,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3877276013935429,0.6753914885244385,0.0,0.270098,0.21629600000000002,0.273409,0.0,0.233511,0.263263,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.001988878811874612,0.0,0.9377453122723773,0.0,1.0,0.0015692096147908426,0.0,0.6854610044650133,0.9177495161736245,0.0015566430772765306,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,7.138906152496655e-42,0.5136423405654185,0.4189767790730379,0.5138879012415911,0.018021497986009438,0.8727481608773724,0.3612371103406806,0.0,0.9982299988666204,0.1334581366789188,0.5602627954031676,0.38481408569634085,0.4574385866037522,0.0,0.04356089694363341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16547741134560373,0.0,0.24778761061946905,0
21671,0.7809048532273191,0.2920755394984752,0.9653384165882813,0.9633609924619537,0.6372679014023135,0.00013173796742171624,0.0,0.0,0.052814626057694714,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.912710042809668,0.19255227986180115,0.05491425463340891,0.07142857142857142,0.155641217357107,0.041711205058709344,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.25245866794254407,0.037314750758749626,0.09302325581395346,0.17021768389297967,0.045509438532037635,0.0,0.233963248754743,0.03959849924168562,0.09302325581395346,0.9840568566376909,0.530495852913232,0.0,0.05371623953085454,0.041381863445045575,0.007812357620115126,0.03719729433633593,0.04550963285006957,0.03684720101407662,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3656740945244188,0.6218272936655826,0.0,0.271308,0.20770700000000003,0.27129200000000003,0.0,0.22835899999999998,0.253356,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.001994174392352126,0.0,0.9361678216894551,0.0,1.0,0.0017464875160121867,0.0,0.6892904865886647,0.9159789921185384,0.001731392422783346,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,6.455393861300166e-42,0.5136423405654185,0.41907053786292536,0.5138879012415911,0.015896812310620456,0.8788737425421402,0.36134846808858123,0.0,0.9982299988666204,0.1191674404474093,0.5539637903876024,0.38492647079060943,0.45833710098077723,0.0,0.03739824911687961,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16606328846842694,0.0,0.24778761061946905,0
21681,0.7810705003476256,0.30664102713517083,0.9653966853404145,0.9634246166877799,0.6370898595812267,0.00013412006030802653,0.0,0.0,0.07203906459557641,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.9151187617240523,0.18311783197166123,0.05047961074924599,0.07142857142857142,0.14943251184156836,0.04225810382322044,0.0697674418604651,1.0,0.007554034064070324,0.09302325581395351,0.25049827847850387,0.03753740232483912,0.09302325581395346,0.1606745269240715,0.04659917405509165,0.0,0.23546863735209717,0.03943218226817793,0.09302325581395346,0.9832531831984466,0.5304162493901342,0.0,0.04836049435138499,0.04224438807751348,0.007812357620115126,0.03775105426600006,0.0463092515514546,0.0364382620608055,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.36159863274830784,0.6651022557609285,0.0,0.272499,0.19879000000000002,0.26952400000000004,0.0,0.22281900000000002,0.24484200000000003,0.0,0.0,1.0,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,0.5,0.5,0.0,0.0,0.001994958257936933,0.0,0.9470416848764855,0.0,1.0,0.0018315920908044117,0.0,0.6978131212723655,0.9202347609717396,0.0018152831313382068,0.0,0.0,0.0,0.0,0.0,0.0,0.1748633268237545,6.657916021654682e-42,0.5136423405654185,0.4192893083726599,0.5138879012415911,0.015884586281073143,0.8608397211870784,0.3608436462980973,0.0,0.9982299988666204,0.055313841190238806,0.5912439612199929,0.3849966541351935,0.45522037923547176,0.0,0.08237981876823675,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16556867863609376,0.0,0.24778761061946905,0

Looks good. Let's move on to the attack data.

In [27]:
# load from disk
attack_data = pd.read_csv(
    path_to_wadi + '/WADI.A2_19 Nov 2019/WADI_attackdataLABLE.csv',
    skiprows=1
)
attack_data

,Row,Date,Time,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,...,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW,"Attack LABLE (1:No Attack, -1:Attack)"
0,1.0,10/9/17,00:00.0,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39,1
1,2.0,10/9/17,00:01.0,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39,1
2,3.0,10/9/17,00:02.0,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39,1
3,4.0,10/9/17,00:03.0,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39,1
4,5.0,10/9/17,00:04.0,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172798,172799.0,10/11/17,59:58.0,172.915,0.583479,11.9211,466.051,0.318317,0.001260,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,58.8102,1.0,0.00,1
172799,172800.0,10/11/17,59:59.0,172.915,0.583479,11.9211,466.051,0.318317,0.001260,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,58.8102,1.0,0.00,1
172800,172801.0,10/11/17,00:00.0,172.915,0.583479,11.9211,466.051,0.318317,0.001260,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,58.8102,1.0,0.00,1
172801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
172802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [28]:
# fix column labels, drop timestamps and last two weird rows
attack_data = (
    attack_data[:-2]
    .rename(
        columns={
            'Row ': 'Row', 
            'Date ': 'Date',
            'Attack LABLE (1:No Attack, -1:Attack)': 'attack'
        }
    )
    .set_index('Row')
    .drop(columns=['Date', 'Time'])
)

# fix index
attack_data.index = attack_data.index.astype('int')

# change attack labels from WADI format (1: no attack, -1:attack) 
# to GDN format (0:no attack: 1:attack)
attack_labels = (
    attack_data['attack'].map(lambda label: 1 if label==-1 else 0)
)

# split labels from data
attack_data = attack_data.drop(columns="attack")

# replace missing values
attack_data = attack_data.fillna(attack_data.mean()).fillna(0)

attack_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
1,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,0.0,48.4820,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39
2,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,0.0,48.4820,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39
3,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,0.0,48.4820,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39
4,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,0.0,48.4820,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39
5,164.210,0.529486,11.9972,482.480,0.331167,0.001273,0.0,0.0,48.4820,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,62.6226,1.0,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172797,172.959,0.547483,11.9184,466.034,0.318217,0.001222,0.0,0.0,55.5587,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,59.3546,1.0,0.00
172798,172.959,0.547483,11.9184,466.034,0.318217,0.001222,0.0,0.0,55.5587,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,59.3546,1.0,0.00
172799,172.915,0.583479,11.9211,466.051,0.318317,0.001260,0.0,0.0,55.7260,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,58.8102,1.0,0.00
172800,172.915,0.583479,11.9211,466.051,0.318317,0.001260,0.0,0.0,55.7260,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,58.8102,1.0,0.00
172801,172.915,0.583479,11.9211,466.051,0.318317,0.001260,0.0,0.0,55.7260,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,58.8102,1.0,0.00

In [29]:
# normalize attack data using training normalizer
attack_normed = normalizer.transform(attack_data.values)
attack_data = pd.DataFrame(
    attack_normed,
    columns=attack_data.columns,
    index=attack_data.index
)

attack_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
1,0.766223,0.257117,0.998660,0.916341,0.575661,0.000225,0.0,0.0,0.294758,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169052,0.0,0.172566
2,0.766223,0.257117,0.998660,0.916341,0.575661,0.000225,0.0,0.0,0.294758,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169052,0.0,0.172566
3,0.766223,0.257117,0.998660,0.916341,0.575661,0.000225,0.0,0.0,0.294758,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169052,0.0,0.172566
4,0.766223,0.257117,0.998660,0.916341,0.575661,0.000225,0.0,0.0,0.294758,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169052,0.0,0.172566
5,0.766223,0.257117,0.998660,0.916341,0.575661,0.000225,0.0,0.0,0.294758,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169052,0.0,0.172566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172797,0.807047,0.265856,0.992100,0.885106,0.514986,0.000200,0.0,0.0,0.510464,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.136980,0.0,0.000000
172798,0.807047,0.265856,0.992100,0.885106,0.514986,0.000200,0.0,0.0,0.510464,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.136980,0.0,0.000000
172799,0.806841,0.283336,0.992325,0.885138,0.515454,0.000218,0.0,0.0,0.515564,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.131638,0.0,0.000000
172800,0.806841,0.283336,0.992325,0.885138,0.515454,0.000218,0.0,0.0,0.515564,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.131638,0.0,0.000000
172801,0.806841,0.283336,0.992325,0.885138,0.515454,0.000218,0.0,0.0,0.515564,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.131638,0.0,0.000000

In [30]:
# downsample features by 10x using median
attack_data = attack_data.rolling(window=10, step=10).median()

attack_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW
Row,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.766228,0.261487,0.998552,0.916335,0.575930,0.000175,0.0,0.0,0.293548,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169016,0.0,0.172566
21,0.766237,0.271683,0.998760,0.916341,0.575675,0.000142,0.0,0.0,0.294935,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169957,0.0,0.172566
31,0.766251,0.270226,0.998743,0.916288,0.576143,0.000197,0.0,0.0,0.294377,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.169334,0.0,0.172566
41,0.766223,0.268770,0.998468,0.916362,0.575708,0.000191,0.0,0.0,0.291649,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.164901,0.0,0.141593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172761,0.807439,0.254204,0.992408,0.884553,0.515614,0.000282,0.0,0.0,0.512470,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.140142,0.0,0.000000
172771,0.807056,0.260030,0.992358,0.884660,0.516481,0.000137,0.0,0.0,0.511129,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.139279,0.0,0.000000
172781,0.807009,0.268770,0.992059,0.884819,0.515398,0.000163,0.0,0.0,0.512046,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.134754,0.0,0.000000
172791,0.806981,0.274597,0.992325,0.884914,0.515754,0.000169,0.0,0.0,0.512653,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.137133,0.0,0.000000
172801,0.807030,0.267313,0.992180,0.885106,0.515141,0.000209,0.0,0.0,0.510905,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.136980,0.0,0.000000

In [31]:
# downsample labels by 10x using max
attack_labels = attack_labels.rolling(window=10, step=10).max()
attack_labels

Row
1         NaN
11        0.0
21        0.0
31        0.0
41        0.0
         ...
172761    0.0
172771    0.0
172781    0.0
172791    0.0
172801    0.0
Name: attack, Length: 17281, dtype: float64

In [32]:
# rejoin data and labels and drop first weird row
attack_data = attack_data[1:].assign(attack=attack_labels[1:].astype(int))
attack_data

,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,...,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW,attack
Row,,,,,,,,,,,,,,,,,,,,,
11,0.766228,0.261487,0.998552,0.916335,0.575930,0.000175,0.0,0.0,0.293548,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.169016,0.0,0.172566,0
21,0.766237,0.271683,0.998760,0.916341,0.575675,0.000142,0.0,0.0,0.294935,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.169957,0.0,0.172566,0
31,0.766251,0.270226,0.998743,0.916288,0.576143,0.000197,0.0,0.0,0.294377,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.169334,0.0,0.172566,0
41,0.766223,0.268770,0.998468,0.916362,0.575708,0.000191,0.0,0.0,0.291649,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.164901,0.0,0.141593,0
51,0.766186,0.254203,0.998851,0.916350,0.575501,0.000201,0.0,0.0,0.289220,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.167520,0.0,0.172566,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172761,0.807439,0.254204,0.992408,0.884553,0.515614,0.000282,0.0,0.0,0.512470,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.140142,0.0,0.000000,0
172771,0.807056,0.260030,0.992358,0.884660,0.516481,0.000137,0.0,0.0,0.511129,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.139279,0.0,0.000000,0
172781,0.807009,0.268770,0.992059,0.884819,0.515398,0.000163,0.0,0.0,0.512046,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.134754,0.0,0.000000,0
172791,0.806981,0.274597,0.992325,0.884914,0.515754,0.000169,0.0,0.0,0.512653,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.137133,0.0,0.000000,0
172801,0.807030,0.267313,0.992180,0.885106,0.515141,0.000209,0.0,0.0,0.510905,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.136980,0.0,0.000000,0

In [33]:
# save to disk
attack_data.to_csv(
    '/content/drive/MyDrive/WADI-processed/test.csv'
)

In [34]:
# sanity check
!head /content/drive/MyDrive/WADI-processed/test.csv

Row,1_AIT_001_PV,1_AIT_002_PV,1_AIT_003_PV,1_AIT_004_PV,1_AIT_005_PV,1_FIT_001_PV,1_LS_001_AL,1_LS_002_AL,1_LT_001_PV,1_MV_001_STATUS,1_MV_002_STATUS,1_MV_003_STATUS,1_MV_004_STATUS,1_P_001_STATUS,1_P_002_STATUS,1_P_003_STATUS,1_P_004_STATUS,1_P_005_STATUS,1_P_006_STATUS,2_DPIT_001_PV,2_FIC_101_CO,2_FIC_101_PV,2_FIC_101_SP,2_FIC_201_CO,2_FIC_201_PV,2_FIC_201_SP,2_FIC_301_CO,2_FIC_301_PV,2_FIC_301_SP,2_FIC_401_CO,2_FIC_401_PV,2_FIC_401_SP,2_FIC_501_CO,2_FIC_501_PV,2_FIC_501_SP,2_FIC_601_CO,2_FIC_601_PV,2_FIC_601_SP,2_FIT_001_PV,2_FIT_002_PV,2_FIT_003_PV,2_FQ_101_PV,2_FQ_201_PV,2_FQ_301_PV,2_FQ_401_PV,2_FQ_501_PV,2_FQ_601_PV,2_LS_001_AL,2_LS_002_AL,2_LS_101_AH,2_LS_101_AL,2_LS_201_AH,2_LS_201_AL,2_LS_301_AH,2_LS_301_AL,2_LS_401_AH,2_LS_401_AL,2_LS_501_AH,2_LS_501_AL,2_LS_601_AH,2_LS_601_AL,2_LT_001_PV,2_LT_002_PV,2_MCV_007_CO,2_MCV_101_CO,2_MCV_201_CO,2_MCV_301_CO,2_MCV_401_CO,2_MCV_501_CO,2_MCV_601_CO,2_MV_001_STATUS,2_MV_002_STATUS,2_MV_003_STATUS,2_MV_004_STATUS,2_MV_005_STATUS,2_MV_006_STATUS,2_MV_009_STATUS,2_MV_101_STATUS,2_MV_201_STATUS,2_MV_301_STATUS,2_MV_401_STATUS,2_MV_501_STATUS,2_MV_601_STATUS,2_P_001_STATUS,2_P_002_STATUS,2_P_003_SPEED,2_P_003_STATUS,2_P_004_SPEED,2_P_004_STATUS,2_PIC_003_CO,2_PIC_003_PV,2_PIC_003_SP,2_PIT_001_PV,2_PIT_002_PV,2_PIT_003_PV,2_SV_101_STATUS,2_SV_201_STATUS,2_SV_301_STATUS,2_SV_401_STATUS,2_SV_501_STATUS,2_SV_601_STATUS,2A_AIT_001_PV,2A_AIT_002_PV,2A_AIT_003_PV,2A_AIT_004_PV,2B_AIT_001_PV,2B_AIT_002_PV,2B_AIT_003_PV,2B_AIT_004_PV,3_AIT_001_PV,3_AIT_002_PV,3_AIT_003_PV,3_AIT_004_PV,3_AIT_005_PV,3_FIT_001_PV,3_LS_001_AL,3_LT_001_PV,3_MV_001_STATUS,3_MV_002_STATUS,3_MV_003_STATUS,3_P_001_STATUS,3_P_002_STATUS,3_P_003_STATUS,3_P_004_STATUS,LEAK_DIFF_PRESSURE,PLANT_START_STOP_LOG,TOTAL_CONS_REQUIRED_FLOW,attack
11,0.7662275851449527,0.26148655866985215,0.9985516053041212,0.916335092653966,0.5759301513824009,0.00017538788290247037,0.0,0.0,0.29354836743153934,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9141772370661876,0.3025846104732321,0.07698462561814168,0.261904761904762,0.6456770328559137,0.09913830897193487,0.046511627906976744,1.0,0.009669599202244368,0.023255813953488386,0.17715652843031482,0.05023167985585392,0.023255813953488358,1.0,0.012261934177953498,0.04545454545454547,1.0,0.01403264297446902,0.1627906976744186,0.0,0.5262571792962363,0.0,0.07547451114176605,0.10012979169637604,0.010000268250102199,0.05036254398581626,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4448990994544122,0.7549883681901823,0.0,0.0,0.0,0.197965,0.0,0.6775645,0.35536599999999996,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0019020767682147257,0.0,0.8775800711743774,0.0,1.0,0.0037546919005391768,0.0,0.6439396408434641,0.8982472062282378,0.0037179212520162706,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,9.227415931152592e-42,0.8218277449046685,0.1197612276150899,0.3750088888256795,0.016685886866270372,0.9633671873491538,0.28819385156754596,0.0,0.9982299988666204,0.12331996867792608,0.5231589712269571,0.6271525873984475,0.5470991777466796,0.0,0.07683151589617498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16901573624734412,0.0,0.17256637168141595,0
21,0.7662369173770828,0.2716833712099139,0.9987597079903108,0.9163407903458309,0.5756748019284741,0.00014245254375790497,0.0,0.0,0.2949352581140725,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9127208442397774,0.2968557031259125,0.07746307932248177,0.261904761904762,0.6145667567698581,0.100443963566872,0.046511627906976744,1.0,0.009669599202244368,0.023255813953488386,0.16728277197223693,0.048590037485406246,0.023255813953488358,1.0,0.012261934177953498,0.04545454545454547,1.0,0.01403264297446902,0.1627906976744186,0.0,0.5219252069263624,0.0,0.07515224125428742,0.09914951043620672,0.010000268250102199,0.04884630451636171,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4478735292184304,0.7685732804018461,0.0,0.0,0.0,0.188262,0.0,0.647761,0.349805,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0019021749010054957,0.0,0.8760025805914551,0.0,1.0,0.0038048520816461847,0.0,0.6427337613662285,0.8993581036410189,0.00376039805845958,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,9.91092822234908e-42,0.8218277449046685,0.1213551270431612,0.3750088888256795,0.016707695459517002,0.9633720144426636,0.2888248788056509,0.0,0.9982299988666204,0.6292163918853578,0.2530979847665664,0.6271970827214843,0.5488176742382846,0.0,0.08979035478420982,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1699573595293355,0.0,0.17256637168141595,0
31,0.7662509157252777,0.27022633684905695,0.9987430597754157,0.916287611888424,0.5761433330365968,0.00019661610700821787,0.0,0.0,0.29437745372966906,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9133869324298537,0.2742774817767215,0.07822540860884494,0.09523809523809526,0.5709340228198926,0.10026508102815189,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.16036344861538132,0.03974079393584344,0.023255813953488358,1.0,0.012261934177953498,0.04545454545454547,1.0,0.01403264297446902,0.1627906976744186,0.0,0.5047282780816407,0.0,0.07613190059325757,0.09978949210849691,0.010000268250102199,0.041250068426279776,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.44291066850719574,0.7845337438224091,0.0,0.0,0.0,0.18151300000000004,0.0,0.608482,0.32986600000000005,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0019049202256643466,0.0,0.8701182077376123,0.0,1.0,0.003968631462792554,0.0,0.641332333865658,0.902683283047445,0.003921841416405841,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,1.0277999637991639e-41,0.8218277449046685,0.1209800918836148,0.3750088888256795,0.01670141722812779,0.9453379930876027,0.2885205009613885,0.0,0.9982299988666204,0.5758822170208943,0.2778460531258856,0.6271200186568431,0.5492783383475992,0.0,0.09293887267700818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16933419039534442,0.0,0.17256637168141595,0
41,0.7662229190288878,0.2687702736825748,0.9984683642296455,0.9163616818826693,0.5757075991060425,0.00019086422418517575,0.0,0.0,0.29164939403545564,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9123859999063877,0.2526974258794562,0.07668789398160834,0.09523809523809526,0.531360911263767,0.09829703139728549,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.1617575717350206,0.0415738704050283,0.1627906976744186,1.0,0.012261934177953498,0.022727272727272763,0.99466701371901,0.01403264297446902,0.023255813953488358,0.0,0.5047162947555829,0.0,0.07740590318937195,0.0999819985955218,0.010000268250102199,0.04166079320211395,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4534608558469735,0.758937975254915,0.0,0.0,0.0,0.182984,0.0,0.57238,0.309311,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0019161025768466933,0.0,0.8856392166656263,0.0,1.0,0.0039844596091132105,0.0,0.6411693771795459,0.9018693929231126,0.003937443802214027,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,1.0670386323678511e-41,0.8218277449046685,0.12069881551395589,0.3750088888256795,0.016695799863200633,0.9513477245081194,0.28907728970089286,0.0,0.9982299988666204,0.010383909354260359,0.6441035803182457,0.6269447896527183,0.5532005641926205,0.0,0.07688911073567617,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16490134790993,0.0,0.1415929203539823,0
51,0.766185590100368,0.25420284365712953,0.9988512731722341,0.9163502864989393,0.5755014454184686,0.0002007847695592609,0.0,0.0,0.2892200492574801,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9133185233724945,0.23141909063342306,0.07571361352629274,0.09523809523809526,0.4917473129074874,0.09739937250670713,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.1639221043195966,0.04066641661860718,0.1627906976744186,1.0,0.012261934177953498,0.022727272727272763,1.0,0.01403264297446902,0.023255813953488358,0.0,0.49631427128538286,0.0,0.0732532303915478,0.09947786369953641,0.010000268250102199,0.04053656362855321,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4356471438900904,0.7119130565618454,0.0,0.0,0.0,0.184986,0.0,0.5355190000000001,0.289296,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0018813827167758195,0.0,0.8772814301471354,0.0,1.0,0.004050461248690849,0.0,0.6398005410161973,0.8986448854643732,0.004002504045138318,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,9.986874032482022e-42,0.8218277449046685,0.1227927618214224,0.3750088888256795,0.016658130474865585,0.9513477245081194,0.2886838256583095,0.0,0.9982299988666204,0.09789667138779894,0.5372639136347359,0.6271356149556395,0.5488115320501604,0.0,0.09472431270158133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16751963964140787,0.0,0.17256637168141595,0
61,0.766180923984303,0.24546306547792474,0.9986514945934922,0.9164053641869679,0.5759465499711853,0.00019086422418517575,0.0,0.0,0.2935148382062476,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9138729967847743,0.22158883715779584,0.07375358640488218,0.09523809523809526,0.47125552084025213,0.0976679525934961,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.16478278812929295,0.040942914186584786,0.1627906976744186,1.0,0.012261934177953498,0.022727272727272763,1.0,0.01403264297446902,0.023255813953488358,0.0,0.4962295320511174,0.0,0.07122332415717943,0.09755587074131447,0.010000268250102199,0.04116117274656303,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.43387234601985014,0.6920058795615787,0.0,0.0,0.0,0.185797,0.0,0.517324,0.280957,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0018888360219089162,0.0,0.8729318848723233,0.0,1.0,0.004093140001511728,0.0,0.6368347293289451,0.9010149335064289,0.004044574061034906,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,1.1189349359586956e-41,0.8218277449046685,0.121167609463388,0.3750088888256795,0.01457970545181786,0.9634782104998942,0.2890327466017326,0.0,0.9982299988666204,0.40661999734703747,0.40807850908315996,0.6269035053323746,0.551438633656423,0.0,0.09445553678390262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1663998979376537,0.0,0.17256637168141595,0
71,0.7661995884485631,0.28624934444379696,0.9984100954775124,0.9164471472606448,0.5763869692128207,0.00020594112916072548,0.0,0.0,0.2936154258821233,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9139162025052118,0.2038608563848632,0.06997043176954834,0.09523809523809526,0.43133225317468493,0.09876687569669365,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.16635643409362455,0.04117349399835106,0.1627906976744186,1.0,0.012261934177953498,0.022727272727272763,1.0,0.01403264297446902,0.023255813953488358,0.0,0.4961259618759041,0.0,0.06873151488366039,0.0992222123541789,0.010000268250102199,0.04186064138433432,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.41796489844212203,0.6340320135183615,0.0,0.0,0.0,0.18735900000000003,0.0,0.48030700000000004,0.263813,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0019006047763531796,0.0,0.8729318848723233,0.0,1.0,0.0041839821129433154,0.0,0.6369325033406117,0.9019094613600029,0.004134120470416787,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,1.1062773009365384e-41,0.8218277449046685,0.12463668468918954,0.3750088888256795,0.014521879636391288,0.9634782104998942,0.28849822941180836,0.0,0.9982299988666204,0.0,0.7271053620192318,0.6269447896527183,0.5452402883836645,0.0,0.08155429273536896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16686801081468322,0.0,0.17256637168141595,0
81,0.7662089206806929,0.2658562049608609,0.9987763562052059,0.9163939688032379,0.5758294171941547,0.00013094393645961288,0.0,0.0,0.295294935258114,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9138657958313681,0.1878610103813533,0.06719178669067576,0.09523809523809526,0.3918554345486559,0.09718307327650688,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.1677023425064036,0.041557683570104885,0.1627906976744186,1.0,0.012261934177953498,0.022727272727272763,1.0,0.01403264297446902,0.023255813953488358,0.0,0.4876297837009646,0.0,0.06531658484792184,0.09569190278804686,0.010000268250102199,0.04131623889464037,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4261815552487995,0.6122498582192333,0.0,0.0,0.0,0.18835200000000002,0.0,0.44533700000000004,0.249447,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0018902098809796925,0.0,0.8608228756945746,0.0,1.0,0.004218567078579198,0.0,0.6294039044421993,0.9030724477407412,0.004168212142687321,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,1.149313260011873e-41,0.8218277449046685,0.120230021564522,0.3750088888256795,0.014587966282593123,0.9514587476588598,0.28866155410872985,0.0,0.9982299988666204,0.5635213370931232,0.2619673845464352,0.627120936086184,0.5488475077234592,0.0,0.06709798802027223,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16250582687674492,0.0,0.17256637168141595,0
91,0.7662369173770828,0.24837737699823237,0.998597387895083,0.9164946280261868,0.5759067248269947,0.00021407510487007794,0.0,0.0,0.29539857104538025,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.9138351917793917,0.17494001274364215,0.06189022777940428,0.09523809523809526,0.35343127272663605,0.09506928648658768,0.0697674418604651,1.0,0.009669599202244368,0.023255813953488386,0.16858046567815574,0.04243111196882983,0.1627906976744186,1.0,0.012261934177953498,0.022727272727272763,1.0,0.01403264297446902,0.023255813953488358,0.0,0.47056552739473934,0.0,0.06079075744354348,0.09591034986552192,0.010000268250102199,0.04248508340520181,0.012261934177953498,0.012999391305674238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4379806744231889,0.6122498582192333,0.0,0.0,0.0,0.189638,0.0,0.409926,0.237299,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.5,0.5,1.0,0.5,1.0,1.0,0.0,0.0,0.0018988407796020261,0.0,0.8786461259911347,0.0,1.0,0.004388749603863697,0.0,0.6263729100805007,0.9028615875916064,0.004357146668226642,0.0,0.0,0.0,0.0,0.0,0.0,0.14207295577776413,1.0923539024121655e-41,0.8218277449046685,0.12126136825327372,0.3750088888256795,0.01660393942498012,0.9513477245081194,0.28814930846838527,0.0,0.9982299988666204,0.5290018014471483,0.28088878538961254,0.6270576334616573,0.548813286961053,0.0,0.09477230840116668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.16213683223992498,0.0,0.17256637168141595,0

Looks good. Last file GDN needs is `list.txt` which just lists column names.

In [43]:
# output column names (sans attack)
with open('/content/drive/MyDrive/WADI-processed/list.txt', 'w') as f:
  for col in training_data.columns[:-1]:
    f.write(col+'\n')

In [44]:
!head '/content/drive/MyDrive/WADI-processed/list.txt'

1_AIT_001_PV
1_AIT_002_PV
1_AIT_003_PV
1_AIT_004_PV
1_AIT_005_PV
1_FIT_001_PV
1_LS_001_AL
1_LS_002_AL
1_LT_001_PV
1_MV_001_STATUS

All looks good so far. I'll try running GDN with these files when the cluster comes back online.